name: GitHub Actions Linux tests

on: [push, pull_request, workflow_dispatch]

jobs:
  ubuntu-vcpkg-cuda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update apt
      run: sudo apt update
    - name: Install dependencies
      run: sudo apt install yasm

    - uses: lukka/get-cmake@latest

    - name: 'Install CUDA'
      env:
        CUDACXX: "/usr/local/cuda-10.2/bin/nvcc"
        CUDA_PATH: "/usr/local/cuda-10.2"
        CUDA_TOOLKIT_ROOT_DIR: "/usr/local/cuda-10.2"
        LD_LIBRARY_PATH: "/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.2/lib64/stubs:$LD_LIBRARY_PATH"
      run: |
        wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.2.89-1_amd64.deb
        sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
        sudo dpkg -i cuda-repo-ubuntu1804_10.2.89-1_amd64.deb
        wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
        sudo dpkg -i nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
        sudo apt update
        sudo apt-get install -y --no-install-recommends cuda-compiler-10-2 cuda-libraries-dev-10-2 cuda-driver-dev-10-2 cuda-cudart-dev-10-2 cuda-curand-dev-10-2
        sudo apt-get install -y --no-install-recommends libcudnn7-dev
        sudo ln -s /usr/local/cuda-10.2/lib64/stubs/libcuda.so /usr/local/cuda-10.2/lib64/stubs/libcuda.so.1

    - name: 'Test CUDA'
      env:
        CUDACXX: "/usr/local/cuda-10.2/bin/nvcc"
        CUDA_PATH: "/usr/local/cuda-10.2"
        CUDA_TOOLKIT_ROOT_DIR: "/usr/local/cuda-10.2"
        LD_LIBRARY_PATH: "/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.2/lib64/stubs:$LD_LIBRARY_PATH"
      run: |
        echo $PATH
        $CUDACXX -V

    - name: Restore from cache and run vcpkg
      env:
        CUDACXX: "/usr/local/cuda-10.2/bin/nvcc"
        CUDA_PATH: "/usr/local/cuda-10.2"
        CUDA_TOOLKIT_ROOT_DIR: "/usr/local/cuda-10.2"
        LD_LIBRARY_PATH: "/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.2/lib64/stubs:$LD_LIBRARY_PATH"
      uses: lukka/run-vcpkg@v6
      with:
        setupOnly: true
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: 'e4ce66eecfd3e5cca5eac06c971921bf8e37cf88'
        appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
        vcpkgTriplet: 'x64-linux'
        additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed

    - name: 'Build with CMake and Ninja'
      env:
        CUDACXX: "/usr/local/cuda-10.2/bin/nvcc"
        CUDA_PATH: "/usr/local/cuda-10.2"
        CUDA_TOOLKIT_ROOT_DIR: "/usr/local/cuda-10.2"
        LD_LIBRARY_PATH: "/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.2/lib64/stubs:$LD_LIBRARY_PATH"
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildDirectory: '${{ runner.workspace }}/buildDirectory'
        cmakeBuildType: 'Release'
        cmakeAppendedArgs: "-DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=OFF"
