name: GitHub Actions macOS tests

on: [push, pull_request, workflow_dispatch]

jobs:
  osx-vcpkg:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: brew install libomp yasm

    - uses: lukka/get-cmake@latest

    - name: Restore from cache and run vcpkg
      uses: lukka/run-vcpkg@v6
      with:
        setupOnly: true
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: 'e4ce66eecfd3e5cca5eac06c971921bf8e37cf88'
        appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
        vcpkgTriplet: 'x64-osx'
        additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed

    - name: 'Build with CMake and Ninja'
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildDirectory: '${{ runner.workspace }}/buildDirectory'
        cmakeBuildType: 'Release'
        cmakeAppendedArgs: "-DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=OFF"
